name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # or any other version you're using

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn build

      - name: Set Git user info
        run: |
          git config --global user.email "priya.grover1988@gmail.com"
          git config --global user.name "priyagrovr"

      - name: Deploy to GitHub Pages
        run: |
          yarn add gh-pages
          yarn run deploy
        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
